# Generated by Django 6.0.1 on 2026-01-19 12:36

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models
from django.conf import settings
from django.db import migrations, models

import GSST.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('arquivo', GSST.fields.SecureFileField(upload_to='arquivos/', verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cr', models.CharField(blank=True, choices=[('71498 - MG - LPG - SRE - VALE CORR SUL LP ITABIRI - (GRSA)', '71498 - MG - LPG - SRE - VALE CORR SUL LP ITABIRI - (GRSA)'), ('74130 - MG - LPG - SRE - VALE CORR SUL LP NOV LIM - (GRSA)', '74130 - MG - LPG - SRE - VALE CORR SUL LP NOV LIM - (GRSA)'), ('71497 - MG - LPG - SRE - VALE CORRE SUL LP BRUMAD - (GRSA)', '71497 - MG - LPG - SRE - VALE CORRE SUL LP BRUMAD - (GRSA)'), ('71496 - MG - LPG - SRE - VALE CORREDOR SUL CONG - (GRSA)', '71496 - MG - LPG - SRE - VALE CORREDOR SUL CONG - (GRSA)'), ('79078 - MG - LPG - SRE - VALE CORR SUL LP NOV LIM - (GRSA)', '79078 - MG - LPG - SRE - VALE CORR SUL LP NOV LIM - (GRSA)'), ('71502 - MG - LPG - SRE - VALE CORR SUL LP OUR PRE - (GRSA)', '71502 - MG - LPG - SRE - VALE CORR SUL LP OUR PRE - (GRSA)'), ('71503 - MG - CAT - SRE - VALE CORR SUL LP NOV LIM - (GRSA)', '71503 - MG - CAT - SRE - VALE CORR SUL LP NOV LIM - (GRSA)')], max_length=255, null=True, verbose_name='CR')),
                ('funcao', models.CharField(blank=True, choices=[('11033 - AJUDANTE DE SERVICOS GERAIS', '11033 - AJUDANTE DE SERVICOS GERAIS'), ('11365 - ENCARREGADO OPERACIONAL', '11365 - ENCARREGADO OPERACIONAL'), ('11626 - SUPERVISOR DE SERVICOS', '11626 - SUPERVISOR DE SERVICOS'), ('11089 - ASSISTENTE ADMINISTRATIVO I', '11089 - ASSISTENTE ADMINISTRATIVO I'), ('11486 - MEDICO DO TRABALHO', '11486 - MEDICO DO TRABALHO'), ('11168 - AUXILIAR DE SERVICOS GERAIS', '11168 - AUXILIAR DE SERVICOS GERAIS'), ('22531 - COORDENADOR OPERACIONAL', '22531 - COORDENADOR OPERACIONAL'), ('11377 - ENGENHEIRO DE SEGURANCA DO TRABALHO', '11377 - ENGENHEIRO DE SEGURANCA DO TRABALHO'), ('11668 - TECNICO DE SEGURANCA DO TRABALHO', '11668 - TECNICO DE SEGURANCA DO TRABALHO'), ('11088 - ASSISTENTE ADMINISTRATIVO', '11088 - ASSISTENTE ADMINISTRATIVO'), ('22189 - TECNICO DE SEGURANCA DO TRABALHO PL', '22189 - TECNICO DE SEGURANCA DO TRABALHO PL')], max_length=255, null=True, verbose_name='Função')),
                ('categoria', models.CharField(blank=True, choices=[('MENSALISTA', 'MENSALISTA')], max_length=255, null=True, verbose_name='Categoria')),
                ('pcd', models.BooleanField(default=False, verbose_name='PCD')),
                ('aprendiz', models.BooleanField(default=False, verbose_name='Aprendiz')),
                ('data_de_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('data_de_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('situacao', models.CharField(choices=[('ADMISSAO FUTURA', 'ADMISSAO FUTURA'), ('ATIVO', 'ATIVO'), ('FERIAS', 'FERIAS'), ('TRANSFERIDO', 'TRANSFERIDO')], default='ATIVO', max_length=255, verbose_name='Situação')),
                ('deve_alterar_senha', models.BooleanField(default=True, verbose_name='Deve alterar senha?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Acesso')),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Usuário')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSST.arquivo', verbose_name='Arquivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
