# Generated by Django 6.0.1 on 2026-03-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacesso',
            name='ip_usuario',
            field=models.TextField(blank=True, null=True, verbose_name='IP do Usuário'),
        ),
    ]
