# Generated by Django 6.0.1 on 2026-01-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(blank=True, choices=[('MENSALISTA', 'MENSALISTA')], max_length=255, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cr',
            field=models.CharField(blank=True, choices=[('71498 - MG - LPG - SRE - VALE CORR SUL LP ITABIRI - (GRSA)', '71498 - MG - LPG - SRE - VALE CORR SUL LP ITABIRI - (GRSA)'), ('74130 - MG - LPG - SRE - VALE CORR SUL LP NOV LIM - (GRSA)', '74130 - MG - LPG - SRE - VALE CORR SUL LP NOV LIM - (GRSA)'), ('71497 - MG - LPG - SRE - VALE CORRE SUL LP BRUMAD - (GRSA)', '71497 - MG - LPG - SRE - VALE CORRE SUL LP BRUMAD - (GRSA)'), ('71496 - MG - LPG - SRE - VALE CORREDOR SUL CONG - (GRSA)', '71496 - MG - LPG - SRE - VALE CORREDOR SUL CONG - (GRSA)'), ('79078 - MG - LPG - SRE - VALE CORR SUL LP NOV LIM - (GRSA)', '79078 - MG - LPG - SRE - VALE CORR SUL LP NOV LIM - (GRSA)'), ('71502 - MG - LPG - SRE - VALE CORR SUL LP OUR PRE - (GRSA)', '71502 - MG - LPG - SRE - VALE CORR SUL LP OUR PRE - (GRSA)'), ('71503 - MG - CAT - SRE - VALE CORR SUL LP NOV LIM - (GRSA)', '71503 - MG - CAT - SRE - VALE CORR SUL LP NOV LIM - (GRSA)')], max_length=255, null=True, verbose_name='CR'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(blank=True, choices=[('11033 - AJUDANTE DE SERVICOS GERAIS', '11033 - AJUDANTE DE SERVICOS GERAIS'), ('11365 - ENCARREGADO OPERACIONAL', '11365 - ENCARREGADO OPERACIONAL'), ('11626 - SUPERVISOR DE SERVICOS', '11626 - SUPERVISOR DE SERVICOS'), ('11089 - ASSISTENTE ADMINISTRATIVO I', '11089 - ASSISTENTE ADMINISTRATIVO I'), ('11486 - MEDICO DO TRABALHO', '11486 - MEDICO DO TRABALHO'), ('11168 - AUXILIAR DE SERVICOS GERAIS', '11168 - AUXILIAR DE SERVICOS GERAIS'), ('22531 - COORDENADOR OPERACIONAL', '22531 - COORDENADOR OPERACIONAL'), ('11377 - ENGENHEIRO DE SEGURANCA DO TRABALHO', '11377 - ENGENHEIRO DE SEGURANCA DO TRABALHO'), ('11668 - TECNICO DE SEGURANCA DO TRABALHO', '11668 - TECNICO DE SEGURANCA DO TRABALHO'), ('11088 - ASSISTENTE ADMINISTRATIVO', '11088 - ASSISTENTE ADMINISTRATIVO'), ('22189 - TECNICO DE SEGURANCA DO TRABALHO PL', '22189 - TECNICO DE SEGURANCA DO TRABALHO PL')], max_length=255, null=True, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='situacao',
            field=models.CharField(choices=[('ADMISSAO FUTURA', 'ADMISSAO FUTURA'), ('ATIVO', 'ATIVO'), ('FERIAS', 'FERIAS'), ('TRANSFERIDO', 'TRANSFERIDO')], default='ATIVO', max_length=255, verbose_name='Situação'),
        ),
    ]
